# -------- Project Name ------------------------------------------------------
PROJECT_NAME=cpp_sapi_basic_example

# -------- Compile options ---------------------------------------------------
VERBOSE=n
OPT=g
USE_FPU=y

# -------- Modules to include ----------------------------------------------
USE_NANO=y
SEMIHOST=n
USE_LPCOPEN=y

# -------- Core makefile -----------------------------------------------------
# You must define your core folder here (relative to this program folder)
CORE_PATH = ../../../ciaa_project/cores/lpc4337

include $(CORE_PATH)/core.mk
