# -------- Project Name ------------------------------------------------------
PROJECT_NAME=mpu9250

# -------- Compile options ---------------------------------------------------
VERBOSE=n
OPT=g
USE_FPU=y

# -------- Modules to include ----------------------------------------------
USE_NANO=n
SEMIHOST=n
USE_LPCOPEN=y
USE_SAPI=y

# -------- Core makefile -----------------------------------------------------
# You must define your core folder here (relative to this program folder)
CORE_PATH = ../../../../../../../ciaa_project/cores/lpc4337

include $(CORE_PATH)/core.mk
