# -------- Project Name ------------------------------------------------------
PROJECT_NAME=freeRTOS_03_ChanFatFS_SPI_SdCard_ADC_log

# -------- Compile options ---------------------------------------------------
VERBOSE=n
OPT=g
USE_FPU=y

# -------- Modules to include ----------------------------------------------
USE_NANO=y
SEMIHOST=n
USE_LPCOPEN=y
USE_SAPI=y
USE_FREERTOS=y
FREERTOS_HEAP_TYPE=1

# -------- Core makefile -----------------------------------------------------
# You must define your core folder here (relative to this program folder)
CORE_PATH = ../../../../../../../ciaa_project/cores/lpc4337

include $(CORE_PATH)/core.mk
